name: ArenaRegen
version: 1.2.7
main: com.zitemaker.ArenaRegen
api-version: 1.18
description: A plugin that registers and regenerates regions using coordinates.
author: Zitemaker Studios
softdepend: ["PlaceholderAPI"]
commands:
  arenaregen:
    description: The base command.
    usage: /arenaregen
    aliases: [ar]

permissions:
  arenaregen.create:
    description: Allows the player to register regions.
    default: op
  arenaregen.delete:
    description: Allows the player to regenerate regions.
    default: op
  arenaregen.resize:
    description: Allows the player to resize regions.
    default: op
  arenaregen.regenerate:
    description: Allows the player to use the selection tool. Receives access to /arenaregen wand & /arenaregen selection
  arenaregen.select:
    description: Allows the player to use the selection tool. Receives access to /arenaregen wand & /arenaregen selection
  arenaregen.list:
    description: Allows the player to list all regions.
    default: op
  arenaregen.info:
    description: Allows the player to view information related to an arena.
    default: op
  arenaregen.setspawn:
    description: Allows the player to set a spawn for regions.
    default: op
  arenaregen.delspawn:
    description: Allows the player to delete a spawn for regions.
    default: op
  arenaregen.teleport:
    description: Allows the player to teleport to region spawns.
    default: op
  arenaregen.reload:
    description: Allows the player to reload the plugin.
    default: op
  arenaregen.help:
    description: Allows the player to view available commands.
    default: true
  arenaregen.preview:
    description: Allows the player to preview an arena.
    default: op